### ISSUE TITLE
Upgrade fails

### ISSUE THREAD

**Issue by rafi1975** [ccrisan/motioneyeos#1003]
Hi,

Just trying to upgrade from the following on raspberry pi3:
motionEye Version	20161212
Motion Version	4.0.1+git37b3595
to the latest release and it fails. Logs below:

[motioneye]     INFO: updating to version 20170611...
2017-06-20 19:53:36: [motioneye]     INFO: killing motioneye init script...
2017-06-20 19:53:36: [motioneye]     INFO: stopping netwatch init script...
2017-06-20 19:53:36: [motioneye]     INFO: downloading https://github.com/ccrisan/motioneyeos/releases/download/20170611/motioneyeos-raspberrypi3-20170611.img.gz...
2017-06-20 19:53:37: [motioneye]    ERROR: could not download update: Command '['/usr/bin/wget', u'https://github.com/ccrisan/motioneyeos/releases/download/20170611/motioneyeos-raspberrypi3-20170611.img.gz', '--no-check-certificate', '-O', '/data/.firmware_update/firmware.gz']' returned non-zero exit status 8
2017-06-20 19:53:37: [motioneye]    ERROR: Command '['/usr/bin/wget', u'https://github.com/ccrisan/motioneyeos/releases/download/20170611/motioneyeos-raspberrypi3-20170611.img.gz', '--no-check-certificate', '-O', '/data/.firmware_update/firmware.gz']' returned non-zero exit status 8
Traceback (most recent call last):
  File "home/ccrisan/motioneyeos/output/raspberrypi3/target/usr/lib/python2.7/site-packages/tornado/web.py", line 1443, in _execute
  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 175, in wrapper
  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 1787, in post
  File "/usr/lib/python2.7/site-packages/motioneye/update.py", line 199, in perform_update
  File "/usr/lib/python2.7/site-packages/motioneye/update.py", line 132, in download
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
CalledProcessError: Command '['/usr/bin/wget', u'https://github.com/ccrisan/motioneyeos/releases/download/20170611/motioneyeos-raspberrypi3-20170611.img.gz', '--no-check-certificate', '-O', '/data/.firmware_update/firmware.gz']' returned non-zero exit status 8
2017-06-20 19:53:37: [motioneye]    ERROR: 500 POST /update/?version=20170611&_=1497984815226&_username=admin&_signature=5f59514976b50889ea2b1e3f15660c0d4ec4e0c6 (192.168.1.167) 1203.10ms

Any idea?

Thanks

**Comment by ccrisan** [comment]
Try upgrading again. It looks like the download of the new image failed for some reason. Make sure you have a working internet connection.
