### ISSUE TITLE
Issue with Software Update

### ISSUE THREAD

**Issue by ReSpector** [ccrisan/motioneyeos#1514]
Hi,
I cannot use "Software Update" to install newer version from GUI (or SSH as far as I can manage)

I have two Raspberry Pi units, model 2 and 3, both behave the same way.
model 2 runs 20171008 (conntected with cable)
and model 3 runs 20180101 (conntected over wifi)

(I did update model 3 before in januari to 20180101 by "Enable Prereleases")

But now the update process finds the latest release, updates, and says all went OK, reboot but upon login the same older version is still the active one.

motioneye.log says:
2018-04-25 01:27:10: [motioneye]     INFO: updating to version 20180401...
2018-04-25 01:27:12: [motioneye]     INFO: stopping motioneye watch script
2018-04-25 01:27:13: [motioneye]     INFO: stopping netwatch script
2018-04-25 01:27:13: [motioneye]     INFO: downloading firmware version 20180401
2018-04-25 01:28:16: [motioneye]     INFO: extracting firmware
2018-04-25 01:28:16: [motioneye]     INFO: flashing boot partition
2018-04-25 01:28:17: [motioneye]    ERROR: Exception in callback <functools.partial object at 0x75531cc0>Traceback (most recent call last):  File "usr/lib/python2.7/site-packages/tornado/ioloop.py", line 605, in _run_callback File "usr/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper File "/usr/lib/python2.7/site-packages/motioneye/platformupdate.py", line 58, in perform_update Exception: firmware flash boot failed

Same behaviour:
https://github.com/ccrisan/motioneyeos/issues/1241

Tried this:
https://github.com/ccrisan/motioneyeos/issues/1323

fwupdate download 20180401
fwupdate extract
	(The .img file is 0 bytes)
fwupdate flashboot
	[root@RPi3 data]# fwupdate flashboot
	flashing boot...
	umount: can't unmount /boot: Invalid argument
	fdisk: cannot open /data/.fwupdate/firmware.img: Inappropriate ioctl for device
	/sbin/fwupdate: line 218: / 2048: syntax error: operand expected (error token is "/ 2048")

gunzip.log say:
gzip: /data/.fwupdate/firmware.img.gz: not in gzip format

I did try extracting with tar but that didn't work.

[root@RPi3 data]# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root               174.3M    165.1M         0 100% /
devtmpfs                433.4M         0    433.4M   0% /dev
tmpfs                   437.9M     16.0K    437.9M   0% /dev/shm
tmpfs                   437.9M    124.0K    437.8M   0% /tmp
/dev/mmcblk0p3           14.3G    132.8M     13.5G   1% /data
/dev/mmcblk0p3           14.3G    132.8M     13.5G   1% /home/ftp/sdcard
/dev/mmcblk0p3           14.3G    132.8M     13.5G   1% /home/ftp/storage

**Comment by ccrisan** [comment]
Please update to `20180224` first. Then you should be able to update to `20180401`. The archive format has been recently changed from `.gz` to `.xz`.

**Comment by ReSpector** [comment]
Thanks! that worked.

**Comment by iguana007** [comment]
Nevermind, I found it ;) https://github.com/ccrisan/motioneyeos/wiki/Troubleshooting
