### ISSUE TITLE
Creating large time-lapse fails

### ISSUE THREAD

**Issue by matucker** [ccrisan/motioneyeos#1581]
MotionEyeOS version 20180627
Raspberry Pi Zero W

I'm currently taking a snapshot every 20 seconds which totals to around 4,316 snapshots a day.  When I try to create a time-lapse to include a picture taken every 10 seconds and frame rate of 20 the process fails.  The progress bars never gets past 0% and the follow error is in my motioneye.log

Traceback (most recent call last):
  File "usr/lib/python2.7/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
  File "usr/lib/python2.7/site-packages/tornado/stack_context.py", line 316, in wrapped
  File "/usr/lib/python2.7/site-packages/motioneye/mediafiles.py", line 645, in poll_media_list_process
  File "/usr/lib/python2.7/site-packages/motioneye/mediafiles.py", line 692, in make_movie
  File "usr/lib/python2.7/subprocess.py", line 390, in __init__
  File "usr/lib/python2.7/subprocess.py", line 1025, in _execute_child
OSError: [Errno 7] Argument list too long

**Comment by ccrisan** [comment]
This is definitely valid but unfortunately I don't know any possible fix for it, other than rewrite the entire functionality in a different way.

**Comment by matucker** [comment]
Would the entire functionality have to be rewritten if we was able to select what time of day we wanted a time lapse from the UI?  Currently it tries to time lapse a whole day, but many times I only need an afternoon.
