### ISSUE TITLE
motionEyeOS 20180101 - update Problem

### ISSUE THREAD

**Issue by hogak** [ccrisan/motioneyeos#1583]
### motionEyeOS Version

**I am running motionEyeOS version:**
motionEyeOS 20180101 
motionEye Version | 0.38
Motion Version | 4.1.1

**Board Model**
Raspi Zero W

**Camera**
Raspi Cam NoIR

**Network Connection**
WLAN

**Problem**
WebUI says 
"New version availabele: 20180627. Update?"
"Updating. This may take a few minutes"
"motionEye was successfully updated!"

motionEyeOS Version still the same as before.

after that, i tryed this:
https://github.com/ccrisan/motioneyeos/issues/1527

and i received this:
fwupdate upgrade 20180224
upgrading to 20180224
downloading..
downloaded 20180224
extracting ..
extracted 20180224
flashing boot ...
unmount: can´t mount /boot: invalid argument
boot read 20180224
preparing for reboot ...

same as via WebUI: motionEyeOS 20180101

### Peripherals
none

### Log Files
motioneye.log
2018-07-14 09:14:17: [motioneye]     INFO: updating to version 20180627...
2018-07-14 09:14:19: [motioneye]     INFO: stopping motioneye watch script
2018-07-14 09:14:19: [motioneye]     INFO: stopping netwatch script
2018-07-14 09:14:19: [motioneye]     INFO: downloading firmware version 20180627
2018-07-14 09:16:35: [motioneye]     INFO: extracting firmware
2018-07-14 09:16:35: [motioneye]     INFO: flashing boot partition
2018-07-14 09:16:36: [motioneye]    ERROR: Exception in callback <functools.partial object at 0xb4a6eb10>
Traceback (most recent call last):
  File "usr/lib/python2.7/site-packages/tornado/ioloop.py", line 605, in _run_callback
  File "usr/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
  File "/usr/lib/python2.7/site-packages/motioneye/platformupdate.py", line 58, in perform_update
Exception: firmware flash boot failed
2018-07-14 09:16:36: [motioneye]    ERROR: mjpg client timed out receiving data for camera 1 on port 8081
2018-07-14 09:16:46: [motioneye]  WARNING: mjpg client connection for camera 1 on port 8081 is closed

**Comment by pagan27** [comment]
Hi! Try this: fwupdate upgrade 20180401 after i can update the new version on my rp2

**Comment by hogak** [comment]
Thx, but 20180401 is not available.
After hours of trying, I finally made it. Can be closed.
