### ISSUE TITLE
20160801 version can't be updated.

### ISSUE THREAD

**Issue by snigel** [ccrisan/motioneyeos#1684]
Running motioneye 20160801 on a RPI1 trying to do an update.
It fails with a generic; "The update process has failed!"

Looking at the log you can see that the wget download fails trying to download,
https://github.com/ccrisan/motioneyeos/releases/download/20180627/motioneyeos-raspberrypi-20180627.img.gz

That url is broken, since only a .img.xz exists. Looking at update.py one can see that the update string is hardcoded to only look for .img.gz

Tried to enable prereleases but that gives another error:
2018-10-20 14:48:44: [motioneye]    ERROR: 500 GET /update/?_=1540046922061&_username=.... (192.168...) 2441.07ms
2018-10-20 14:48:58: [motioneye]    ERROR: invalid literal for int() with base 10: 'nightly-dev'
Traceback (most recent call last):
  File "home/ccrisan/motioneyeos/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/web.py", line 1443, in _execute
  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 166, in wrapper
  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 1744, in get
  File "/usr/lib/python2.7/site-packages/motioneye/update.py", line 86, in compare_versions
ValueError: invalid literal for int() with base 10: 'nightly-dev'
2018-10-20 14:48:58: [motioneye]    ERROR: 500 GET /update/?_=1540046936875&_username=admin&_signature=8bf09e1ba3e8dc968c34ef412ad5c459bbd09c45 (192.168...) 2338.24ms

Is there any way I can patch the installation so I can perform an update without reinstalling?

**Comment by ccrisan** [comment]
Update incrementally to intermediate versions. If that doesn't work, write the OS from scratch.

**Comment by ccrisan** [comment]
@snigel I'm really sorry that you had/still have to climb a ladder and physically intervene on your RPi unit, but things have changed considerably in two years. We simply cannot provide full backwards compatibility between all versions, no matter how old.

**Comment by snigel** [comment]
@ccrisan no blame intended! Sorry if it looked that way.
Big thanks for the support and software.
