### ISSUE TITLE
Motion issue connecting to Google Drive

### ISSUE THREAD

**Issue by narimanmani** [ccrisan/motioneyeos#1811]
When obtain and insert the token and press the test, it says its scucessfull. Sometimes it also creates the folder and upload some clips...but it will stops after few minutes with below error. Any hint?

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: motionEye v0.3.0
 Simple, elegant and feature-rich CCTV/NVR for your cameras
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
 armhf / HassOS 1.13 / HA 0.86.3 / SU 143 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirement.sh: executing... 
[cont-init.d] 10-requirement.sh: exited 0.
[cont-init.d] 20-init-configuration.sh: executing... 
[cont-init.d] 20-init-configuration.sh: exited 0.
[cont-init.d] 21-init-media.sh: executing... 
[cont-init.d] 21-init-media.sh: exited 0.
[cont-init.d] 30-nginx.sh: executing... 
[cont-init.d] 30-nginx.sh: exited 0.
[cont-init.d] 31-motion.sh: executing... 
[cont-init.d] 31-motion.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
    INFO: hello! this is motionEye server 0.39.3
    INFO: cleanup started
    INFO: wsswitch started
    INFO: tasks started
    INFO: mjpg client garbage collector started
    INFO: smb mounts started
    INFO: server started
/bin/sh: lsb_release: not found
 WARNING: 403 GET /login/?_=1549479713289&_username=_&_signature=687d2180af2534e3b00f806e90764fcb67f8e800 (127.0.0.1) 13.89ms
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 408, in _handle_results
    cache[job]._set(i, obj)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 577, in _set
    self._callback(self._value)
  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 837, in _on_test_result
    request_handler.finish_json()
  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 115, in finish_json
    self.finish(json.dumps(data))
  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 98, in finish
    RequestHandler.finish(self, chunk=chunk)
  File "/usr/lib/python2.7/site-packages/tornado/web.py", line 1052, in finish
    future = self.flush(include_footers=True)
  File "/usr/lib/python2.7/site-packages/tornado/web.py", line 994, in flush
    start_line, self._headers, chunk, callback=callback)
  File "/usr/lib/python2.7/site-packages/tornado/http1connection.py", line 413, in write_headers
    self._pending_write = self.stream.write(data)
  File "/usr/lib/python2.7/site-packages/tornado/iostream.py", line 587, in write
    self._handle_write()
  File "/usr/lib/python2.7/site-packages/tornado/iostream.py", line 1085, in _handle_write
    if not len(self._write_buffer):
TypeError: object of type 'NoneType' has no len()
 WARNING: mjpg client connection for camera 1 on port 8081 is closed
   ERROR: failed to upload file "/cameras/driveway/2019-02-06/13-31-49.mp4" with service gdrive: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/motioneye/uploadservices.py", line 876, in upload_media_file
    service.upload_file(target_dir, filename)
  File "/usr/lib/python2.7/site-packages/motioneye/uploadservices.py", line 93, in upload_file
    data = f.read()
MemoryError
```

**Comment by ccrisan** [comment]
Are you sure this is motionEyeOS? It surely doesn't look so. Also you totally ignored the issue template and did not mention the required details.
