### ISSUE TITLE
Some problems with notifications, image upload.

### ISSUE THREAD

**Issue by rolfep** [ccrisan/motioneyeos#2040]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: 20190427.

### Board Model

I am using the following board/model: Pi Zero W.

### Camera

I am using the following type of camera:  MMAL

My camera model is:   Pi Noir

### Network Connection

My motionEyeOS unit is connected to the network via: WiFi:  Netgear Unite Aircard 770S

 

### Peripherals

I am using the following peripherals that I consider relevant to this issue:

 * (e.g. USB WiFi adapter)
 * (e.g. External Hard Disk)

### Log Files

I consider the following log files relevant to this issue:

 * (attach e.g. motioneye.log)
[motioneye.log](https://github.com/ccrisan/motioneyeos/files/3491088/motioneye.log)

 
My friend in a senior housing apartment is convinced the maintenance man is letting himself in with a master key when she goes out and stealing from her.  Management is hostile and the police can't act without evidence.  I'm trying to set up a low-power motion-activated camera with battery backup and MiFi hotspot for the router.  She has no internet.  This is my first opportunity to play with a Pi, so a lot is foreign.  The Aircard is on 192.168.2.1 while my LAN router is at 192.168.1.1, so I'm using an old 32-bit VAIO running Puppy Linux to access motioneyeos with static IP set.  It's slow all around but I am getting _some_ notifications with pictures attached sent to my gmail account and uploaded to gdrive.  The goal is to upload the potential evidence before someone potentially sees and steals the contraption, so speed of the operation is important.

Watching the camera feed in a browser or moving in the field of view myself, some events are not apparently sent out/uploaded or what seems to me should be multiple images for a given event only produces one.  I can see the frame of the feed light up red.  Sometimes the notification comes but there are long periods with no uploaded images.

I've left sensitivity high for initial testing, so there are a lot of files on the sd card.  I started to get a string of motion notification emails with the message but no attachments, which brought me to the issue of "ERROR: timeout waiting for the media listing process to finish".  I deleted all the files on the card to get beyond that but I'm concerned I won't be there to do that when this goes online.  Does the notification attachment process search anywhere but in the folder created for the current day?  I need to do something that will automatically avoid this problem.

On the lack of expected notification, I see, in the motioneye.log, 
```
2019-08-11 20:26:08: [sendmail]    ERROR: failed to send mail: Server not connected
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/motioneye/sendmail.py", line 225, in on_message
  File "/usr/lib/python2.7/site-packages/motioneye/sendmail.py", line 80, in send_mail
  File "usr/lib/python2.7/smtplib.py", line 749, in sendmail
  File "usr/lib/python2.7/smtplib.py", line 511, in data
  File "usr/lib/python2.7/smtplib.py", line 332, in send
SMTPServerDisconnected: Server not connected
2019-08-11 20:26:21: [sendmail]     INFO: email sent
2019-08-11 20:33:13: [sendmail]     INFO: sending email
```
It seems hit or miss.  Test emails typically succeed.

In order to keep it simple for my friend,the Pi Zero W, Aircard, RavPower battery pack, camera, 5-12V up-converter for the IR illuminator, cables and a switch are packed pretty tightly into a small box;
![IMG_20190810_160607](https://user-images.githubusercontent.com/7839157/62848864-28f67b80-bc92-11e9-84f6-e966f8a13fd4.jpg)
My thinking went to possible overheating and I found this:
```
#!/bin/bash

cpuTemp0=$(cat /sys/class/thermal/thermal_zone0/temp)
cpuTemp1=$(($cpuTemp0/1000))
cpuTemp2=$(($cpuTemp0/100))
cpuTempM=$(($cpuTemp2 % $cpuTemp1))
echo CPU Temp"="$cpuTemp1"."$cpuTempM""
echo 10 1>&2
``` 
here:  https://github.com/ccrisan/motioneye/wiki/Monitoring-Commands

Wanting something more immediate than an overlay on the images, I just put it in /data/etc and called it.  The result seemed legit but didn't repeat, so I gave it to 'watch':

```
Every 2s: ./hot                                                2019-08-11 23:36:17

CPU Temp=62.6
10
```
When I checked it was reporting about 63 degrees.

Do you see something I can change to make it work better? 
Thanks.
Rolf

**Comment by rolfep** [comment]
I want to try to flesh this out a little bit with some overlooked or new details.

*  Over the past couple of days, I had the HTTP port set to 8888 in a yet unsuccessful attempt to do port forwarding in the Unite router.  Thinking the perceived upload problems might have something to do with that, I disabled port forwarding in the router and reverted the port to 80 in motioneyeos just before making my first post.
*  Also just before my first post, when test uploads to gdrive were failing, I re-did the authorization.

My observations of the notification/upload behavior were made while logged into ssh plus the motioneyeos web page and Unite Manager in the Seamonkey browser on the laptop.  I wonder if this further burden to the frail machines might affect the performance.

Overnight, I turned off the laptop and let the box run, pointed outdoors where nocturnal animals come through to browse the buffet I put out.  This morning, I checked cpu temp with "hot" and it is staying around 62-64 degrees.  For whatever reason, the emails that came had 3, 4, and 5 attachments, which is good for not missing evidence.  

Aside:

> Does the notification attachment process search anywhere but in the folder created for the current day?

If only in the most recent folder, maybe I could give the folders an hourly name to prevent build-up,
`snapshot_filename %Y-%m-%d-%H/%M-%S`
or some such?

It looks to me like the photos uploaded to gdrive were taken very frequently, for some reason; I'll look at motioneyeos settings after writing this.  However, the google time stamp seems to be 10-15 or so minutes after the photo timestamp.  If this represents an actual delay to load the images on the drive server, that would not be so good:
![20190812_075329-drive](https://user-images.githubusercontent.com/7839157/62883363-c1b7e600-bce8-11e9-8f3b-2e17ba697b50.png)

Grepping the sendmail server error in the motioneye.log from a few hours ago, I don't see a particular pattern:
```
2019-08-11 15:21:59: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-11 15:38:27: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-11 20:01:51: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-11 20:07:49: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-11 20:26:08: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-11 21:27:46: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-11 21:31:35: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-11 21:32:33: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-11 21:34:49: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-11 21:36:43: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-11 21:38:37: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-11 21:39:55: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-11 21:47:44: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-11 21:49:50: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-11 21:51:40: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-11 21:58:26: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-11 21:58:50: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-11 21:58:58: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-11 22:01:27: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-11 22:02:49: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-11 22:04:17: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-11 22:07:05: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-11 22:07:51: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-11 22:09:19: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-11 22:12:19: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-12 04:28:18: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-12 04:30:23: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-12 04:47:40: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-12 04:50:46: [sendmail]    ERROR: failed to send mail: Server not connected
2019-08-12 04:57:31: [sendmail]    ERROR: failed to send mail: Server not connected
```
I'll attach that log plus motioneye.conf (where I've added `list_media_timeout_email 20`) along with password-redacted versions of camera-1.conf and motion.conf:

[20190812-motioneye.log](https://github.com/ccrisan/motioneyeos/files/3493621/20190812-motioneye.log)
[20190812-confs.zip](https://github.com/ccrisan/motioneyeos/files/3493648/20190812-confs.zip)

Thanks.

**Comment by rolfep** [comment]
I haven't just been resting on my laurels (_what_ laurels??)!
A progress report might be in order, possibly instructive.  My concerns about the low horsepower of Pi Zero W, justified or not, led me to buy a [Pi 3 B+](https://www.adafruit.com/product/3775), along with [a bigger housing](https://www.michaels.com/artminds-wood-trunk-9x10x14/10383532.html?cm_mmc=PLASearch-_-google-_-MICH_Shopping_US_N_Crafts%26Hobbies_N_N_N_N-_-Crafts+%26+Hobbies&gclid=CjwKCAjw8NfrBRA7EiwAfiVJpZ_BZZM55zDcumZ1IuGcybnWXtcNehuGGkgZTJ0HLJvFXrfSR7lybxoCxeAQAvD_BwE), brighter [LED illuminator](https://smile.amazon.com/gp/product/B07CJDJ3VP/ref=ppx_yo_dt_b_asin_title_o03_s01?ie=UTF8&psc=1), "fancier" [5V-12V up-converter](https://www.amazon.com/DROK-Voltage-Converter-Transformer-Regulator/dp/B074R7FDCR/ref=sr_1_5?keywords=USB+5v+to+DC+12v+Step+Up+Converter&qid=1565672163&s=electronics&sr=1-5) for the illuminator, plus various USB and ZIF flat cables to make a somewhat sane installation.
![20190828_220037](https://user-images.githubusercontent.com/7839157/64538423-738b0800-d2d1-11e9-8cdc-e68292cfcdb7.jpg)
![20190828_220102](https://user-images.githubusercontent.com/7839157/64538424-738b0800-d2d1-11e9-83f3-1017463eddbf.jpg)
Still concerned about the practical lifetime of the [RAVPower Li-Po 22000mAh Battery Pack](https://smile.amazon.com/gp/product/B01G1XH46M/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1) as UPS during a theoretical power outage, I picked up an [IR-CUT camera](https://smile.amazon.com/gp/product/B0768Z87JF/ref=ppx_yo_dt_b_asin_title_o07_s00?ie=UTF8&psc=1) that powers the LEDs off the camera cable.
As the lamps get pretty hot, I mounted them with thermal tape to aluminum stock as heat sink and attached that to the box with [Velcro adhesive fastener](https://www.homedepot.com/p/VELCRO-Brand-4-ft-x-2-in-Industrial-Strength-Tape-90593/202261931).
![20190902_120549-ir-cut-mount](https://user-images.githubusercontent.com/7839157/64540298-cfa35b80-d2d4-11e9-93ed-c88c5de3463c.jpg)

Finally, I installed Raspbian Buster on the card and Motion into that, per the [Wiki](https://github.com/ccrisan/motioneye/wiki/Install-On-Raspbian).

Observations:

- I've stopped image upload to google drive with the result, I believe, that email notifications with motion-triggered image attachments are more likely to come almost immediately.
- While checking my public WAN IP on the Pi, using something like, "curl ifconfig.me", with the intent of setting up port forwarding/remote access, I see that T-Mobile is changing it every few seconds, making that strategy impossible.  At last, I've fairly easily set up a remote desktop that looks to be reliable with [RealVNC](https://www.realvnc.com/).
- Although I've tested the battery pack to run overnight with the LEDs showing still half-full, fwiw, the lights never turn off.  
- To reduce data consumption of the monthly allotment, I need to turn some thing(s) on when my friend leaves the apartment and off when she returns.  My first thought was to switch the Pi and MiFi off, having installed a ["High Endurance" Video Monitoring Card](https://smile.amazon.com/gp/product/B00V5Q1K3O/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1) for the os, for whatever insurance that might provide.  Alternatively, I could just leave the Pi run and turn off the [MiFi router](https://smile.amazon.com/gp/product/B00BLTCZ70/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1), which also leaves those hot LEDs on all the time, visibly red.  One more idea is to switch illuminators to the 12V model with upconverter, which switches itself off, turn the router on/off and leave the Pi running.  I'll have to test how that does running overnight.

**Comment by rolfep** [comment]
I didn't intend to close as it seems to me a W.I.P.
