### ISSUE TITLE
Ä Ö Ü  not working in FTP Path

### ISSUE THREAD

**Issue by Github197** [ccrisan/motioneyeos#2740]
When putting under File Storage in Location a path with letters like ä ö ü FTP and SFTP are not working (maybe other services as well).

Error messages is:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 20: ordinal not in range(128)

In uploadservices.json the following path can be found:
...Pflanzen\u00fcberwachung...

In the interface I entered:
...Pflanzenüberwachung...

I am using:
   motionEye Version | 0.42.1
   Motion Version | 4.2.2+gitUNKNOWN
   OS Version | motionEyeOS 20200606

**Comment by foocp** [comment]
for me it fails when the SFTP password has a non-ascii character. 

> UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 0: ordinal not in range(128)
2021-09-20 10:16:40: [motioneye]    ERROR: failed to upload file "/data/output/Camera1/2021-09-20/10-16-35.jpg" with service sftp: 'ascii' codec can't encode character u'\xf6' in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/motioneye/uploadservices.py", line 1103, in upload_media_file
  File "/usr/lib/python2.7/site-packages/motioneye/uploadservices.py", line 103, in upload_file
  File "/usr/lib/python2.7/site-packages/motioneye/uploadservices.py", line 989, in upload_data
  File "/usr/lib/python2.7/site-packages/motioneye/uploadservices.py", line 1041, in _get_conn


I changed it to ascii and then it worked


edit: the above is from /var/log/motioneye.log
I am using
motionEye Version | 0.42.1
Motion Version | 4.3.1
OS Version | motionEyeOS dev20201026

**Comment by starbasessd** [comment]
Known issue.
