### ISSUE TITLE
Something has broken within the update functionality

### ISSUE THREAD

**Issue by starbasessd** [ccrisan/motioneyeos#2941]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: both 20200606 and dev20201026

### Board Model

I am using the following board/model:Any  Raspberry Pi model from Pi1, 2, 3, 4 and Zero personally tested

### Camera

I am using the following type of camera: (choose from V4L2, MMAL, Network Camera, Fast Network Camera and Simple MJPEG Camera).

My camera model is: Any, IP, USB and CSI cameras tested.

### Network Connection

My motionEyeOS unit is connected to the network via: Ethernet or WiFi.

### Peripherals

I am using the following peripherals that I consider relevant to this issue: N/A

 * (e.g. USB WiFi adapter)
 * (e.g. External Hard Disk)

### Log Files

I consider the following log files relevant to this issue:

 * (attach e.g. motioneye.log)
 * (attach e.g. boot.log)
 Pertinent part of motioneye.log:
> 2022-09-25 05:52:18: [motioneye]    ERROR: failed to list versions: Command 'fwupdate versions' returned non-zero exit status 5
> Traceback (most recent call last):
>  File "/usr/lib/python2.7/site-packages/tornado/web.py", line 1590, in _execute
>  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 205, in wrapper
>  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 1850, in get
>  File "/usr/lib/python2.7/site-packages/motioneye/update.py", line 106, in get_all_versions

>  File "/usr/lib/python2.7/site-packages/motioneye/platformupdate.py", line 38, in get_all_versions
> Exception: failed to list versions: Command 'fwupdate versions' returned non-zero exit status 5
> 2022-09-25 05:52:18: [motioneye]    ERROR: 500 GET /update/?

[messages2.log](https://github.com/motioneye-project/motioneyeos/files/9640477/messages2.log)
[dmesg2.log](https://github.com/motioneye-project/motioneyeos/files/9640478/dmesg2.log)
[motioneye2.log](https://github.com/motioneye-project/motioneyeos/files/9640475/motioneye2.log)

**Comment by starbasessd** [comment]
BTW, my oops: When you press Software Update: Check, whether or not you have 'Enable Pre-Releases' enabled, you get error box stating An error has occurred Refreshing is recommended.

**Comment by Grandma-Betty** [comment]
+1, same here on RaspiPi 4.

**Comment by starbasessd** [comment]
@Grandma-Betty Has to do with where the update files are located since they 'renamed' the tree within github.
