### ISSUE TITLE
MotioneeyeOS - ERROR: 'mask' - fail change remote motioneye Raspberry Pi Zero camera settings

### ISSUE THREAD

**Issue by marcusobrien** [ccrisan/motioneyeos#2974]
### Preliminary Docs

I confirm that I have read the [CONTRIBUTING](https://github.com/ccrisan/motioneyeos/blob/master/.github/CONTRIBUTING.md) guide before opening this issue.

I confirm that I have read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ) before opening this issue.

### motionEyeOS Version

I am running motionEyeOS version: (insert your version here 0.42.1

### Board Model

I am using the following board/model: (insert your board model here, e.g. Raspberry PI 3B+).

Raspberry Pi Zero W
Raspberry Pi Zero 2 W

### Camera

I am using the following type of camera: 

Network Camera

Its the 
Remote motionEye Camera

My camera model is: (insert your camera model, e.g. Logitech C290).
Raspberry Pi V3 IR camera

### Network Connection

My motionEyeOS unit is connected to the network via: (choose your network connection, e.g. WiFi, Ethernet).

Main MotionEyeOS Web Server - Ethernet LAN Cable
Client RPi Zero Cameras - Wifi

### Peripherals

I am using the following peripherals that I consider relevant to this issue:

Using the web services through a Windows 10 PC, using Firefox or MS Edge browsers give the same errors.

I consider the following log files relevant to this issue:

MotionEye OS Server MAIN SERVER - Log file (motioneye.log)

2023-01-21 23:13:03: [motioneye]    ERROR: failed to set config for remote camera 1 on http://192.168.0.116/config/1: internal server error
2023-01-21 23:13:03: [motioneye]    ERROR: on_finish_wrapper() got an unexpected keyword argument 'error'
Traceback (most recent call last):
  File "usr/lib/python2.7/site-packages/tornado/web.py", line 1548, in _stack_context_handle_exception
  File "usr/lib/python2.7/site-packages/tornado/stack_context.py", line 339, in wrapped
  File "/usr/lib/python2.7/site-packages/motioneye/remote.py", line 79, in wrapper
  File "/usr/lib/python2.7/site-packages/motioneye/remote.py", line 237, in on_response
TypeError: on_finish_wrapper() got an unexpected keyword argument 'error'
2023-01-21 23:13:03: [motioneye]    ERROR: 500 POST /config/0/set/?_=1674342781536&_username=admin&_signature=d111111111111111111111111111111f5de51ac8 (192.168.0.70) 92.34ms

I change the above signature etc

MotionEye OS Client side log file (motioneye.log)

2023-01-21 22:56:06: [motioneye]    ERROR: 'mask'
Traceback (most recent call last):
  File "usr/lib/python2.7/site-packages/tornado/web.py", line 1548, in _stack_context_handle_exception
  File "usr/lib/python2.7/site-packages/tornado/web.py", line 1756, in wrapper
  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 297, in post
  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 205, in wrapper
  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 537, in set_config
  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 376, in set_camera_config
  File "/usr/lib/python2.7/site-packages/motioneye/config.py", line 940, in motion_camera_ui_to_dict
KeyError: 'mask'
2023-01-21 22:56:07: [motioneye]    ERROR: 500 POST /config/1/set/?_username=admin&_admin=true&_signature=65a891842253114b4b0cbdd7407e61d70c85a2f4 (192.168.0.156) 97.07mr
r: 'mask'

**Comment by marcusobrien** [comment]
Looking at the web portal hub options in the browser, and I can see the reason.

The Pi Zero W, and the Pi Zero W2 both do not have the **Privacy Mask** option inside the **Video Device**

So when the web request json gets parsed by mtion on the remote camera side, it cant find the mask key.

Is there a way to change this so it works somehow, without having to update anything ?

**Comment by marcusobrien** [comment]
I think I used 2 different versions of the motioneyeos, and although the Pi Zero W 2 is working with a different version to the web hub server - the Pi Zero W is not.

Pi Binary MotionEye Image
motioneyeos-raspberrypi-20200606.img

Pi 3 Binary MotionEye Image
motioneyeos-raspberrypi3-dev20201026.img

As this is what I see when I view the web page of each camera locally - my central hub motioneyeos is the Pi 3 one.

**Raspberry Pi Zero W** 
motionEye Version | 0.42.1
Motion Version | 4.2.2+gitUNKNOWN
OS Version | motionEyeOS 20200606

Then the newer Pi Zero 2 W

**Raspberry Pi Zero W 2** 
motionEye Version | 0.42.1
Motion Version | 4.3.1
OS Version | motionEyeOS unknown

Then the hub server Pi 3

**Raspberry Pi 3**
motionEye Version | 0.42.1
Motion Version | 4.3.1
OS Version | motionEyeOS dev20201026

Have fixed this by putting the matching Pi Zero W image on the zeros, same as the Pi 3 web server motioneye

motioneyeos-raspberrypi3-dev20201026.img
