### ISSUE TITLE
"no device" when starting wifi on RPi Zero 2 W on Jaspers image

### ISSUE THREAD

**Issue by derolly** [ccrisan/motioneyeos#3065]
When trying to boot Jaspers Image for the Raspberry Pi Zero 2 W I get the following error:

` * Detecting disk device: /dev/mmcblk0
 * Checking data filesystem: done
 * Mounting filesystems: done
 * Mounting overlay filesystems: done
 * Loading kernel modules: done
 * Setting hostname: done
 * Configuring CPU frequency: done
 * Starting syslogd: done
 * Loading device-tree overlays: done
 * Starting throttle watcher: done
 * Starting eudev: done
 * Starting watchdog: done
 * Starting rngd: done
 * Preparing AP interfaces: none
 * Starting wpa_supplicant: no device
 * Configuring wireless network: no device
 * Configuring wired network: no device`

I get this error on 2 different boards with this image. Using the official Raspbian Image I do not get this error. I also tried this on 2 differently named wifi networks with the same result. When using a usb-to-network adapter it boots sucessfully. I checked then that the wpa_supplicant.conf was written correctly, and it was.

Any ideas? Maybe a missing driver or something?

**Comment by starbasessd** [comment]
Sounds like a corrupted image. The whole point of @jawsper s image is because the 'official' motionEyeOS images don't have support for the wifi chip on the PiZero2W.

**Comment by starbasessd** [comment]
Can you post your wpa_supplicant.conf file (blot out the SSID and password)
Make sure that the wpa_supplicant.conf doesn't end with .txt if created on a Win10 machine. 
Is it the same file that is copied to the /boot partition on the RPiOS image?

**Comment by derolly** [comment]
The content of my wpa_supplicant.conf:

`country=DE
update_config=1
ctrl_interface=/var/run/wpa_supplicant

network={
	scan_ssid=1
	ssid="MYSSID"
	psk="MYPASSWD"
}`

and the extension is just .conf not .txt

I downloaded the image again, and tried it with balenaEtcher and the Raspberry Pi Imager. No success.

Is it possible that I do not have the same wifi chip as you? How can I check that?

**Comment by starbasessd** [comment]
You are sure you have the PiZero2W card? What does it have for model number on the back?
I haven't heard of any 'newer' models, yet.
You state the PiZero2Ws connect on wifi using RaspberryPiOS? Without the usb to ethernet adapter?
Also assuming the ` at the beginning of the first line and end of the last line are not in the actual file...

**Comment by derolly** [comment]
I'm pretty sure. I bought them here: https://www.elektor.de/raspberry-pi-zero-2-w

Added some photos of one of the boards
![3037](https://user-images.githubusercontent.com/31779133/148587585-2c3eb1c1-374e-49d7-a8f9-b7884717b110.jpg)
![IMG_20220107_185737](https://user-images.githubusercontent.com/31779133/148587591-906905ed-b675-48f0-b029-4a57bbe0aa1d.jpg)

.

**Comment by MStcz** [comment]
Hi Derolly, I am facing very same issue.
Here is the link to img I am trying: 

https://github.com/jawsper/motioneyeos/releases/download/20211113/motioneyeos-raspberrypi3.img.gz


And here what is containing wpa_supplicant.conf file. I have used Linux enters "LF".

country=CZ
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
ssid="ssid"
psk="psswd"
}

**Comment by starbasessd** [comment]
For parsing issues, can you move the country=CZ to the 3rd line?
Can you add key_mgmt=WPA-PSK to the line after psk= and before }

**Comment by MStcz** [comment]
Hi Starbasessd,

just tested with the same result.

Here is the config file:
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=CZ

network={
ssid="ssid"
psk="passwd"
key_mgmt=WPA-PSK
}

Console output:
- booting motionEyeOS unknown
* Detecting disk device: /dev/mncblko
* Creating data partition: done
* Formatting data partition: done
* Mounting data partition: done
* Copying data skeleton: done
* Mounting filesystems: done
* Mounting overlay filesystems: done
* Setting empty root password: done
* Copying version file: done
* Setting UTC timezone: done
* Loading kernel modules: done
* Setting hostname: done
* Configuring CPU frequency: done
* Starting syslogd: done
* Loading device-tree overlays: done
* Starting throttle watcher: done
* Starting eudeu: done
* Starting watchdog: done
* Starting rngd: done
* Preparing AP interfaces: none
* Starting wpa _supplicant: no device
* Configuring wireless network: no device
* Configuring wired network: no device
panic: rebooting (caused by network)
- shutting down motionEyeOS unknown
* Stopping motioneye: failed
* Stopping smbd: failed
* Stopping nbd: failed
* Stopping proftpd: failed
* Stopping sshd: failed
* Stopping crond: failed
* Stopping ntpd: failed
* Stopping network: done
* Stopping pa_supplicant: done
* Stopping rngd: done
* Stopping eudev: done
* Stopping throttle watcher: done
* Stopping syslogd: done
The system is going down NOW!
Sent SIGTERM to all processes
Sent SIGKILL to all processes
Requesting system reboot

**Comment by starbasessd** [comment]
If it were an official image, I'd be questioning:
/dev/mncblko
that would be /dev/mmcblk0 , but maybe @jawsper has an idea?

**Comment by MStcz** [comment]
Sorry, /dev/mncblko is my fault. I took a picture of the screen and did OCR. I can see "0" (zero) on the picture but OCR wrote it as "o". Again sorry for this confusing.

**Comment by jawsper** [comment]
Hi @MStcz, can you check if there's a file called `bcm2710-rpi-zero-2.dtb` in your boot partition? (the same as where you put the `wpa_supplicant.conf`)

**Comment by MStcz** [comment]
Hi @jawsper, it is there. MD5 of the file is  E3C5B4E88C84C8351E8FD44C4FCD652B.

**Comment by jawsper** [comment]
Hmm that matches the one I have. Have you tried running the official Raspberry Pi OS on this specific Pi, to rule out a hardware issue?

**Comment by derolly** [comment]
On my two Pi zero 2 w the official Raspbian Buster runs perfect. Thats what I'm using motioneye on right now. But your image still does not work with both zero 2 w.

**Comment by MStcz** [comment]
This image is working with the same wpa_supplicant.conf config file.
https://downloads.raspberrypi.org/raspios_armhf/images/raspios_armhf-2021-11-08/2021-10-30-raspios-bullseye-armhf.zip

**Comment by dvandijk** [comment]
I'm having the same issue with zero results in changing the wpa_supplicant.conf (I've tried them all). I have another Pi Zero2 which is working fine. Using that image doesn't work either.

The only difference between the Pi Zero2's are the version and chip serial.

Working: version 1.5 with chip serial 210340G
Not working: version 2.11 with chip serial 210340E 

*edit Both are working fine with bullseye by the way.

**Comment by starbasessd** [comment]
@dvandijk 
Interesting. Can you post a pic of both PiZero2W backs (where it shows the version number)? I have been told in the RPi forums that there aren't 2 versions, but that would explain why there are more and more issues...

**Comment by jawsper** [comment]
Ah that is very interesting! Seems there could be a new chip revision, possibly requires another rpi-firmware update.

**Comment by dvandijk** [comment]
Sure, hope this helps

![comparison](https://user-images.githubusercontent.com/592762/150166675-28778432-11f2-418e-b7ed-96322813dadc.jpg)

**Comment by jawsper** [comment]
Interesting, the main CPU does seem to be identical, but perhaps they had to update the Wifi chip. I'll build an image with the latest firmware later tonight.

**Comment by starbasessd** [comment]
@dvandijk Any chance you could get the identifying info off the silver WiFi chips? Please?

**Comment by jawsper** [comment]
@dvandijk Can you try this new version? https://github.com/jawsper/motioneyeos/releases/tag/20220119-dev
I updated rpi-firmware (not sure if needed) and rpi-wifi-firmware (this may fix your issue).

**Comment by jawsper** [comment]
(I'm not near my Pi so this image is not tested by me)

**Comment by derolly** [comment]
I tried the image and can confirm that it works on my pi! Thank you @jawsper 👍

**Comment by dvandijk** [comment]
Can also confirm that it works! Thanks indeed @jawsper

**Comment by MStcz** [comment]
Hi @jawsper, great job, thank you for the solution.

**Comment by john3parker** [comment]
HI @jawsper, thank you for the build. It works for my PiZero2W when other builds would not. However, applying config changes to the camera with you build yields this error for my Remote MotionEye Camera.

2022-01-30 03:02:17: [motioneye]    ERROR: 'privacy_mask'
Traceback (most recent call last):
  File "usr/lib/python2.7/site-packages/tornado/web.py", line 1548, in _stack_context_handle_exception
  File "usr/lib/python2.7/site-packages/tornado/web.py", line 1756, in wrapper
  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 297, in post
  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 205, in wrapper
  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 537, in set_config
  File "/usr/lib/python2.7/site-packages/motioneye/handlers.py", line 376, in set_camera_config
  File "/usr/lib/python2.7/site-packages/motioneye/config.py", line 834, in motion_camera_ui_to_dict
KeyError: 'privacy_mask'
2022-01-30 03:02:17: [motioneye]    ERROR: 500 POST /config/1/set/?_username=admin&_admin=true&_signature=adb1e6260cf73e1d5c822e8f0aba57e1f72fa5b9 (192.168.1.31) 15.75ms

**Comment by starbasessd** [comment]
I do notice an inconsistent use of "/" leading (missing in the first 2 lines), maybe a bad edit?
Are both motionEyes running on PiZero2Ws? Or which is which?

**Comment by john3parker** [comment]
> I do notice an inconsistent use of "/" leading (missing in the first 2 lines), maybe a bad edit? Are both motionEyes running on PiZero2Ws? Or which is which?

I doubled check and was able to reproduce the missing "/" - its not a bad edit. I am running PiZero2W. 

![20220129_202258](https://user-images.githubusercontent.com/6379963/151855503-eafbc54b-ee9c-4933-b21b-4f9c8b02dc28.jpg)

**Comment by starbasessd** [comment]
@jawsper thoughts?

**Comment by john3parker** [comment]
@jawsper Looks like this is a missing `privacy_mask` setting in config.py for _set_default_motion_camera. This sets the default camera_config (line 567) and sent to motion_camera_ui_to_dict (line 570) but privacy_mask doesn't have a default value. It's referenced on line 834 and the error is thrown. May want to solve for this by setting an initial value for privacy_mask = False and the checking for the True/False instead whether the value actually exists. 
I'm not a Python developer and not really sure how the packaging/builds work or I'd give that a try myself.

**Comment by john3parker** [comment]
More debugging - I'm running a central server with MotionEye web frontend server and an attached MotionEyeOS camera. Configuring the camera directly from the camera IP it works fine. The request payload clearly has entries privacy_mask and privacy_mask_lines. 
```
{
  "enabled": true,
  "name": "Camera11",
  "proto": "mmal",
  "auto_brightness": false,
  "rotation": "0",
  "framerate": "2",
  "privacy_mask": false,
  "privacy_mask_lines": [],
  "extra_options": [],
  "storage_device": "custom-path",
```

When I try to configure the camera from the MotionEye frontend server it throws the privacy_mask error. Here you can see the request payload is missing the privacy_mask attribute.
```
{
    "enabled": true,
    "name": "Camera11",
    "proto": "motioneye",
    "auto_brightness": false,
    "rotation": "0",
    "framerate": "2",
    "extra_options": [],
    "storage_device": "custom-path",
```

**Comment by john3parker** [comment]
I'm running the local MotionEye server from a [docker container](https://github.com/ccrisan/motioneye/wiki/Install-In-Docker). It's version is 0.42. There seems to be a mismatch in versions between these builds. Can you update the docker image with the latest version?
```
#      
# meyectl -v
motionEye 0.42
# 

```
The camera is running version 0.42.1 
```
[root@meye-2854046f ~]# meyectl -v
motionEye 0.42.1
[root@meye-2854046f ~]# 
```

**Comment by starbasessd** [comment]
How are you logging into the docker container to run meyectl -v? 
What does the WebGUI report for the docker container as to version for motion, motionEye, and OS?

**Comment by starbasessd** [comment]
Nevermind. 
Confirmed 0.42.0 for the docker image. Along with motion 4.2.2 and OS Ubuntu 18.10.
Checking the Install in Docker [Build Instructions](https://github.com/ccrisan/motioneye/wiki/Install-In-Docker#build-instructions), will report shortly.

**Comment by starbasessd** [comment]
OK, Build Docker gives motionEye 0.42.1, but motion 4.1.1, and OS is Debian 10. Will look at it further...

**Comment by starbasessd** [comment]
I do not have enough time to figure out how to add the binary from motion-project, rather than the default motion from the Debian 10 repo used by the docker build... Anyone want to make suggestions, I'll be happy to re-write the Install in Docker instructions to update them. It is much more viable for the 'average' user (read: script kiddie like me) to build the latest docker than build a motionEyeOS image.

**Comment by jawsper** [comment]
So the version of motioneye on motioneyeos doesn't seem to be actually 0.42.1, there just hasn't been a bump to the version numbers since then, but @ccrisan did update motioneye since then, and that privacy mask feature was added after the 0.42.1 release. The actual version is [1b04e8968c2a127b23341575ab80e9892893b576](https://github.com/ccrisan/motioneye/tree/1b04e8968c2a127b23341575ab80e9892893b576)

**Comment by starbasessd** [comment]
dev20201026 does have the privacy mask option & 0.42.1, with motion 4.3.1. Privacy Mask in motion first appeared 4.1

**Comment by starbasessd** [comment]
Working on adding motion 4.3.2-1 to amd64 Dockerfile build. Suggestions on how to add [1b04e8968c2a127b23341575ab80e9892893b576](https://github.com/ccrisan/motioneye/tree/1b04e8968c2a127b23341575ab80e9892893b576)?

**Comment by starbasessd** [comment]
If there is any interest, I can try for updating to Bullseye, or including RPi specific changes, too... I am not anywhere near a Dev or Programmer, but want to extend usability as long as possible, and the docker container may be the way to go for motionEye.

**Comment by starbasessd** [comment]
OK, have new Dockerfile working, gives Debian 10 (Buster) OS, latest motionEye (with Privacy Mask) and motion 4.3.2-1 
>    attached as Dockerfile.zip 
>    unzip  and place in motioneye/extra folder replacing existing Dockerfile

Command to build:

>     docker build --build-arg VCS_REF=$(git rev-parse HEAD) \
>         --build-arg BUILD_DATE=$(date +"%Y-%m-%dT%H:%M:%SZ") \
>         -t ccrisan/motioneye:master-amd64 -f extra/Dockerfile .
> 

command to run:
>    docker run --name="motioneye" -p 8765:8765 --hostname="motioneye" \
>        -v /etc/localtime:/etc/localtime:ro \
>        -v /etc/motioneye:/etc/motioneye \
>        -v /var/lib/motioneye:/var/lib/motioneye \
>        --restart="always" \
>        --detach=true ccrisan/motioneye:master-amd64
 
If someone would test it, and let me know it's working as expected, I will then add to Install in Docker documentation. 

[Dockerfile.zip](https://github.com/ccrisan/motioneye/files/8009217/Dockerfile.zip)

**Comment by john3parker** [comment]
@starbasessd i was able to build with the new Dockerfile and deploy the container. Everything appears to be working perfectly for me. MotionEye 0.42.1 (with Privacy Mask) and motion 4.3.2. My host operating system is Ubuntu 20.04. I was able to add and update cameras from MotionEye server. Looks good to me! Thank you for doing all the heavy lifting!

**Comment by fils02** [comment]
Hi @jawsper, hi @starbasessd I found your build for motioneyeos rpi0 2 w, and I tried to run but it seems not connecting to wifi even if I tried a lot of times with different wpa_supplicant files. Then I found this topic about the two version of chip and realized that mine is a third one version!
I was wondering if you could add a new version for this, it'll be very helpful for me!

 chip serial RP3A0-AU
                    2104
                 201221A

Thank you very much in advance

**Comment by Slipery** [comment]
Looks like this problem has raised its head again.  Pi Zero 2W marked as version 4.6
on boot up I get 
Starting wpa _supplicant: no device
Configuring wireless network: no device
Configuring wired network: no device
panic: rebooting (caused by network)

**Comment by C4pric** [comment]
hi @jawsper, I have a Raspberry pi zero 2w and I have the same problems as many, my wpa_supplicant file does not detect any service. I would like to know if it was possible to update motioneyes for rpi2w. My raspberry 2w is part of version 4.2.

**Comment by Rileyjarvis** [comment]
@jawsper hi there im having issues were wireless is not an option in the boot up it goes wired network no devices rebooting caused by network my raspi zero 2w is -
RP3A0-AU
2413
240206B
and is v4.6 
![WhatsApp Image 2024-12-27 at 13 57 23_16f36a36](https://github.com/user-attachments/assets/a3bfff31-45b4-447e-9d68-2195ca8e8098)
![WhatsApp Image 2024-12-27 at 13 57 23_ed0acdec](https://github.com/user-attachments/assets/0ced2b64-99df-455f-8072-d74fa0ba6df2)
![WhatsApp Image 2024-12-27 at 13 59 09_171078dc](https://github.com/user-attachments/assets/daf36534-fc32-43c8-a4fe-1bfc9b59dc21)

**Comment by RedKeyEng** [comment]
Joined GitHub solely to say that after 2 days trying everything, modifying wpa_supplicant files to various formats, I've discovered that Raspberry Pi Imager doesn't work with this image. Use only Balena Etcher when flashing the image. Worked perfectly for me.

**Comment by Rileyjarvis** [comment]
Ill try this tonight when home 👍 ill keep it updated

**Comment by Rileyjarvis** [comment]
> Joined GitHub solely to say that after 2 days trying everything, modifying wpa_supplicant files to various formats, I've discovered that Raspberry Pi Imager doesn't work with this image. Use only Balena Etcher when flashing the image. Worked perfectly for me.

Still having issues even with a fresh image of jasper's version of the os just incase it got messed up and its still doing it ive used the flasher you said to use at it had no difference it still panics and reboots due to network (no device found)
Im wondering if theres an update for the chip i haven't found yet or if ive cooked it with octopi which ran perfectly fine while i needed it pervious.

**Comment by jawsper** [comment]
For any of these kind of issues, can you also make sure to test with a regular Raspbian/Raspberry Pi OS image, just to exclude any hardware issues?

**Comment by Rileyjarvis** [comment]
> For any of these kind of issues, can you also make sure to test with a regular Raspbian/Raspberry Pi OS image, just to exclude any hardware issues?

Yea sure ill try that now any particular version i should try?

**Comment by Rileyjarvis** [comment]
> For any of these kind of issues, can you also make sure to test with a regular Raspbian/Raspberry Pi OS image, just to exclude any hardware issues?

Wifi works and everything on raspberry pi os

**Comment by rbscycle** [comment]
I have 2 Pi zero w's with motioneyeos working properly.  Switched to a Pi zero 2 w.  The cameras are on and working except wont save images.  Used Etcher on the Pi3 jasper image. Prepared and copied wpa_supplicanr.conf file.  wont boot:
---- booting motionEyeOS unknown ----
 * Detecting disk device: /dev/mmcblk0
 * Creating data partition: done
 * Formatting data partition: done
 * Mounting data partition: done
 * Copying data skeleton: done
 * Mounting filesystems: done
 * Mounting overlay filesystems: done
 * Setting empty root password: done
 * Copying version file: done
 * Setting UTC timezone: done
 * Loading kernel modules: done
 * Setting hostname: done
 * Configuring CPU frequency: done
 * Starting syslogd: done
 * Loading device-tree overlays: done
 * Starting throttle watcher: done
 * Starting eudev: done
 * Starting watchdog: done
 * Starting rngd: done
 * Preparing AP interfaces: none
 * Starting wpa_supplicant: no device
 * Configuring wireless network: no device
 * Configuring wired network: no device
---- shutting down motionEyeOS unknown ----

**Comment by MichaIng** [comment]
A known issue since the motionEyeOS image uses a too old kernel.

Let me move this issue to the respective repository.

EDIT: Ah it is about the image from Jasper that is supposed to work. Still fits better here.

**Comment by rbscycle** [comment]
I have the same issue with my Pi02w.  I've tried wpa_supplicant with no progress.  I've also tried DietPi (Trixie) with some progress, but in the end just different (unsolvable) problems.  I have the Pi02w partially working with the MotionEyeOS, but I can't get it to save...yet!
