### ISSUE TITLE
Banana Pi CSI camera not selectable in GUI

### ISSUE THREAD

**Issue by ektus** [ccrisan/motioneyeos#470]
As of this weekend, I've got a CSI camera for my Banana PI to play with. After some struggle with missing dependencies, I was able to get MotionEye to start, but it fails as soon as I try to add the camera. The "Add Camera..." dialogue shows in red "An error occured. Refereshing recommended" across the top half of the screen, and the list box for the camera is empty. Here's the corersponding output on the BPi:

```
root@bananapi ~ #     INFO: hello! this is motionEye server 0.33.1
 WARNING: you have motion installed, but no v4l-utils
    INFO: main config file /etc/motioneye/motion.conf does not exist, using default values
    INFO: cleanup started
    INFO: wsswitch started
    INFO: tasks started
    INFO: mjpg client garbage collector started
    INFO: server started
   ERROR: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1425, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1627, in wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/motioneye/handlers.py", line 225, in get
    self.list()
  File "/usr/local/lib/python2.7/dist-packages/motioneye/handlers.py", line 166, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/motioneye/handlers.py", line 591, in list
    cameras = [{'id': d[1], 'name': d[2]} for d in v4l2ctl.list_devices()
  File "/usr/local/lib/python2.7/dist-packages/motioneye/v4l2ctl.py", line 52, in list_devices
    p = subprocess.Popen(['v4l2-ctl', '--list-devices'], stdout=subprocess.PIPE, bufsize=1)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
   ERROR: 500 GET /config/list/?_=1471804762704&username=&password=&proto=v4l2&_username=admin&_signature=d1e68793b5ceff2ccf4be8bc2edf14ff5dd23053 (192.168.0.22) 63.97ms
root@bananapi ~ # 

```

**Comment by ccrisan** [comment]
What version is this?
