### ISSUE TITLE
Problem to install Motioneye on Ubuntu 16.04LTS

### ISSUE THREAD

**Issue by richardsith** [ccrisan/motioneyeos#669]
I've a problem to install Motioneye on Ubuntu 16.04Lts Server, that one is a VM on VMware Fusion.
I saw the guide here 

[here](https://github.com/ccrisan/motioneye/wiki/Install-On-Ubuntu)

but after the step 3 when I run the pip command receive that error:

```
**$: pip install motioneye**
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

thanks a lot

**Comment by richardsith** [comment]
I move that [here](https://github.com/ccrisan/motioneye/issues/404), i wrong place
